# Generated by Django 3.2.12 on 2022-11-30 17:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KZ', verbose_name='Emergency Contact Number'),
        ),
    ]
