# Generated by Django 3.2.12 on 2022-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221207_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
