# Generated by Django 3.2.12 on 2022-11-30 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_emergency_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin_number', models.CharField(max_length=12, verbose_name='IIN Number')),
                ('id_number', models.CharField(max_length=20, verbose_name='ID Number')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('surname', models.CharField(max_length=128, verbose_name='Surname')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Middle Name')),
                ('department_id', models.PositiveIntegerField(verbose_name='Department ID')),
                ('specialization_details_id', models.PositiveIntegerField(verbose_name='Specialization Details ID')),
                ('experience_years', models.IntegerField(verbose_name='Experience Years')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='doctors/photos/', verbose_name='Photo')),
                ('category', models.CharField(max_length=128, verbose_name='Category')),
                ('price_per_appointment', models.IntegerField(verbose_name='Price Per Appointment')),
                ('schedule_details', models.CharField(max_length=256, verbose_name='Schedule Details')),
                ('degree', models.CharField(max_length=128, verbose_name='Degree')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('homepage_url', models.CharField(blank=True, max_length=256, verbose_name='Homepage URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
            },
        ),
    ]
